{% set name = "harmony" %}
{% set version = "1.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: 'r-{{ name|lower }}'
  version: '{{ version }}'

source:
  git_url: 'https://github.com/immunogenomics/{{ name|lower }}.git'
  git_rev: 'master'

build:
  merge_build_host: True # [win]
  number: 0 # if new build for the same version, increment the build number.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  # Other packages to be added:
  # - r-seurat
  # - bioconductor-singlecellexperiment
  # - bioconductor-biocstyle
  # {{posix}}zip build requirement for [win]
  build:
    - {{ posix }}zip
  host:
    - r-base
    - r-rlang
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppprogress
    - r-matrix
    - r-dplyr
    - r-tidyr
    - r-tibble
    - r-ggplot2
    - r-cowplot
    - r-irlba
    - r-knitr
    - r-markdown
    - r-testthat
  run:
    - r-base
    - r-rlang
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppprogress
    - r-matrix
    - r-dplyr
    - r-tidyr
    - r-tibble
    - r-ggplot2
    - r-cowplot
    - r-irlba
    - r-knitr
    - r-markdown
    - r-testthat

test:
  commands:
    # You can put additional test commands to be run here.
    - '$R -e "library(''{{ name }}'')"'           # [not win]
    - "\"%R%\" -e \"library('{{ name }}')\""      # [win]
  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.
  # requires:
    # Put any additional test requirements here.

about:
  home: 'https://github.com/immunogenomics/{{ name }}'
  license: MIT
  summary: 'Scalable integration of single cell RNAseq data for batch correction and meta analysis.'
  description: 'Scalable integration of single cell RNAseq data for batch correction and meta analysis.'
