{% set name = "hyprcoloc" %}
{% set version = "1.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: 'r-{{ name|lower }}'
  version: '{{ version }}'

source:
  git_url: 'https://github.com/jrs95/{{ name|lower }}.git'
  git_rev: 'master'

build:
  merge_build_host: True # [win]
  number: 0 # if new build for the same version, increment the build number.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  # {{posix}}zip build requirement for [win]
  build:
    - {{ posix }}zip
  host:
    - r-base
    - r-iterpc
    - r-rcpp
    - r-rcppeigen
    - r-rmpfr
    - r-matrix
  run:
    - r-base
    - r-iterpc
    - r-rcpp
    - r-rcppeigen
    - r-rmpfr
    - r-matrix

test:
  commands:
    # You can put additional test commands to be run here.
    - '$R -e "library(''{{ name }}'')"'           # [not win]
    - "\"%R%\" -e \"library('{{ name }}')\""      # [win]
  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.
  # requires:
    # Put any additional test requirements here.

about:
  home: 'https://github.com/jrs95/{{ name }}'
  license: MIT
  summary: 'This package is used to perform multi-trait colocalisation analyses using HyPrColoc.'
  description: 'This package is used to perform multi-trait colocalisation analyses using HyPrColoc.'
