{% set name = "PhenoGraph" %}
{% set version = "1.1.14" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: 'https://github.com/jacoblevine/{{ name }}.git'
  git_rev: 'master'

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python
    - setuptools
    - numpy
    - scipy
    - scikit-learn
    - psutil
  run:
    - pip
    - python
    - setuptools
    - numpy
    - scipy
    - scikit-learn
    - psutil

about:
  home: https://github.com/jacoblevine/PhenoGraph
  license: MIT
  summary: Subpopulation detection in high-dimensional single-cell data
