{% set name = "proxysnps" %}
{% set version = "0.0.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: 'r-{{ name|lower }}'
  version: '{{ version }}'

source:
  git_url: 'https://github.com/slowkow/{{ name|lower }}.git'
  git_rev: 'master'

build:
  merge_build_host: True # [win]
  number: 0 # if new build for the same version, increment the build number.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  # {{posix}}zip build requirement for [win]
  build:
    - {{ posix }}zip
  host:
    - r-base
    - r-rcurl
    - bioconductor-myvariant
  run:
    - r-base
    - r-rcurl
    - bioconductor-myvariant

test:
  commands:
    # You can put additional test commands to be run here.
    - '$R -e "library(''{{ name }}'')"'           # [not win]
    - "\"%R%\" -e \"library('{{ name }}')\""      # [win]
  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.
  # requires:
    # Put any additional test requirements here.

about:
  home: 'https://github.com/slowkow/{{ name }}'
  license: MIT
  summary: 'Get proxy SNPs for a SNP in the 1000 Genomes Project.'
  description: 'This package implements functions to query remote VCF files. You can use it to find proxy SNPs in linkage disequilibrium with SNPs of interest or to calculate allele frequencies in different populations.'
